### ISSUE TITLE
The Elder Scrolls Online hangs during the intro sequence

### ISSUE THREAD

**Issue by LiquidPL** [zfigura/wine#13]
The game manages to start, and go through the intro videos, but halfway there it hangs and stops responding until killed.

[Download link for the logs](https://drive.google.com/open?id=1mmHWgUjoasz_ymieJm0C9FkVT08j94M-).

Using the build of wine provided by Steam's [Proton](https://github.com/ValveSoftware/Proton) bundle.

Not sure if this is related to #7, I'll try to compile a fresh build to see if it fixes anything and report back.

**Comment by zfigura** [comment]
Upstream hasn't picked 04b738c yet; I'll make sure it does post haste. The symptoms in the log look about the same, so I'm going to close this one as duplicate. Thanks for reporting.

**Comment by LiquidPL** [comment]
Thanks a lot!
