### ISSUE TITLE
[QUESTION] Why do not you merge Esync with Wine Staging or Wine development branch?

### ISSUE THREAD

**Issue by zefkerr** [zfigura/wine#18]
@zfigura hi! Thank you very much for you greatest work!
But why you do not merge Esync with Wine Staging or Wine development branch?
Regards

**Comment by zfigura** [comment]
There are some aspects of the design of these patches (namely, use of shared memory) and of their functionality (namely, that PulseEvent() and wait-all can't quite work right) that won't be acceptable upstream. As such I am afraid the patchset will always have to remain out-of-tree.
