### ISSUE TITLE
x11drv_main.c:(.text+0x1bfa): undefined reference to `__wine_esync_set_queue_fd'

### ISSUE THREAD

**Issue by Hello71** [zfigura/wine#21]
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: x11drv_main.o: in function `set_queue_display_fd':
x11drv_main.c:(.text+0x1bfa): undefined reference to `__wine_esync_set_queue_fd'
collect2: error: ld returned 1 exit status
winegcc: x86_64-pc-linux-gnu-gcc failed
make[1]: *** [Makefile:1269: winex11.drv.so] Error 2
```

Am using staging, but that is hopefully irrelevant?

**Comment by Hello71** [comment]
wait, I didn't scroll enough, it still breaks with --as-needed

**Comment by Hello71** [comment]
you know what, I dunno what's going on, but if you could help that would be great :)

**Comment by zfigura** [comment]
What commands did you use to build? Make sure that libntdll.cross.a is rebuilt.

**Comment by Hello71** [comment]
OK, so it still doesn't work, and I'm *pretty* sure I'm not using --as-needed. I also tried with -j1 and it still didn't work: https://gist.github.com/Hello71/ecdcf84ddecac34a47a82f3316792c59 (ebuild at the bottom).

**Comment by Hello71** [comment]
I incorrectly rebased the patch, so it didn't update the spec file correctly.
