### ISSUE TITLE
server/esync.c:272:75: warning: format '%ld' expects argument of type 'long int', but argument 4 has type 'off_t' {aka 'long long int'} [-Wformat=]

### ISSUE THREAD

**Issue by Hello71** [zfigura/wine#22]
in 32-bit mode, off_t is long long. minor issue but worth fixing.

**Comment by zfigura** [comment]
> in 32-bit mode, off_t is long long. minor issue but worth fixing.

Says you ;-)

More seriously, I'm not inclined to think so; anyway there are bigger problems with the patch set.
