### ISSUE TITLE
The Elder Scrolls Online hangs after a few seconds on login screen

### ISSUE THREAD

**Issue by gonX** [zfigura/wine#7]
Game starts and gets to the login screen, but after a few seconds it hangs, until the games crash reporter finishes, at which point the game gets closed silently.
No related messages in system logs.

The command run in a clean WINEPREFIX:
`WINEDEBUG=+seh,+pid,+esync,+server,+timestamp WINEESYNC=1 wine eso64.exe > winedebug.log 2>&1`

The produced log file can be found here: [winedebug.log.gz](https://github.com/zfigura/wine/files/2280313/winedebug.log.gz). I closed the game's crash reporter early to help end the log sooner.

Other notable configuration:
- Arch Linux
- Linux-ck patchset
- numfiles 1048576

Please let me know if there is anything else I can do.

**Comment by zfigura** [comment]
Thanks for the report. This should be fixed by 04b738c80700db215594ab5584cc8e9afcb0eb5c; can you please retest?

**Comment by gonX** [comment]
Can confirm I can get past the login screen. Game has been running successfully for a few minutes in a significant city.

Thanks for the quick fix!

**Comment by gonX** [comment]
I just want to point out that this was tested directly from the `esync` branch (which is running 3.10?), and not by using the patchfiles from the releases. I'm not a git expert but the front page of the commits says "14 days ago" despite 04b738c.

I have the game running with the latest patchfiles as well, so the issue does not need re-opening.
